-- MySQL Script generated by MySQL Workbench
-- 12/31/15 16:40:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chargedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chargedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chargedb` DEFAULT CHARACTER SET utf8 ;
USE `chargedb` ;

-- -----------------------------------------------------
-- Table `chargedb`.`user_sys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chargedb`.`user_sys` ;

CREATE TABLE IF NOT EXISTS `chargedb`.`user_sys` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_pass` VARCHAR(45) NOT NULL,
  `user_role` TINYINT NOT NULL DEFAULT 2 COMMENT '用户角色：1.根管理员 2.普通用户',
  `user_regdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_active` BIT NULL DEFAULT 1 COMMENT '用户状态：0为无效 1为有效',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_name` USING BTREE (`user_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chargedb`.`customer_sys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chargedb`.`customer_sys` ;

CREATE TABLE IF NOT EXISTS `chargedb`.`customer_sys` (
  `customer_sysid` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NOT NULL,
  `customer_type` TINYINT NOT NULL COMMENT '商家类别：1.供应商  2.销售商',
  `customer_regtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `customer_id` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_sysid`),
  UNIQUE INDEX `cus_name_type` USING BTREE (`customer_name` ASC, `customer_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chargedb`.`product_sys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chargedb`.`product_sys` ;

CREATE TABLE IF NOT EXISTS `chargedb`.`product_sys` (
  `product_sysid` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NULL,
  `product_type` VARCHAR(25) NULL COMMENT '产品型号',
  `product_speci` VARCHAR(25) NULL COMMENT '规格',
  `product_unit` VARCHAR(25) NULL COMMENT '产品计量单位',
  `product_utprice` FLOAT NULL COMMENT '含税单价',
  `product_unprice` FLOAT NULL COMMENT '不含税单价',
  `product_remark` VARCHAR(55) NULL,
  `product_id` VARCHAR(45) NULL,
  PRIMARY KEY (`product_sysid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chargedb`.`order_sys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chargedb`.`order_sys` ;

CREATE TABLE IF NOT EXISTS `chargedb`.`order_sys` (
  `order_sysid` INT NOT NULL AUTO_INCREMENT,
  `order_id` VARCHAR(45) NULL COMMENT '订单号命名规则：时间戳+标志（X0:单产品全税 X1：单产品无税 ,X表示第几个产品，从1开始）',
  `order_userid` INT NULL,
  `order_custid` INT NULL,
  `order_prdid` INT NULL,
  `order_tprice` FLOAT NULL COMMENT '总价',
  `order_type` TINYINT NULL COMMENT '订单类别：1. 待支出 2.待收入 3.支出 4.收入',
  `order_remark` VARCHAR(255) NULL,
  `order_istaxed` BIT NULL DEFAULT 1 COMMENT '该订单中产品是否含税:0不含税 1含税',
  `order_notedate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `order_mbflag` TINYINT NULL DEFAULT 0 COMMENT '订单中涉及的要素变动情况：0正常 1user被删除（失效）2cust被删除（失效）4prod被删除（失效），多种情况可相加',
  PRIMARY KEY (`order_sysid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chargedb`.`custhis_sys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chargedb`.`custhis_sys` ;

CREATE TABLE IF NOT EXISTS `chargedb`.`custhis_sys` (
  `custhis_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NOT NULL,
  `customer_type` TINYINT NOT NULL COMMENT '商家类别：1.供应商  2.销售商',
  `customer_regtime` TIMESTAMP NULL,
  `custhis_deltime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `customer_id` VARCHAR(45) NULL,
  PRIMARY KEY (`custhis_id`),
  UNIQUE INDEX `cus_name_type` USING BTREE (`customer_name` ASC, `customer_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chargedb`.`orderhis_sys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chargedb`.`orderhis_sys` ;

CREATE TABLE IF NOT EXISTS `chargedb`.`orderhis_sys` (
  `orderhis_sysid` INT NOT NULL AUTO_INCREMENT,
  `order_id` VARCHAR(45) NULL,
  `order_userid` INT NULL,
  `order_custid` INT NULL,
  `order_prdid` INT NULL,
  `order_tprice` FLOAT NULL COMMENT '总价',
  `order_type` TINYINT NULL COMMENT '订单类别：1. 待支出 2.待收入 3.支出 4.收入',
  `order_remark` VARCHAR(255) NULL,
  `order_notedate` TIMESTAMP NULL,
  `order_istaxed` BIT NULL DEFAULT 1 COMMENT '该订单中产品是否含税:0不含税 1含税',
  `orderhis_reason` VARCHAR(255) NULL,
  `orderhis_userid` INT NULL,
  `orderhis_dealtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `order_mbflag` TINYINT NULL DEFAULT 0 COMMENT '订单中涉及的要素变动情况：0正常 1user被删除（失效）2cust被删除（失效）4prod被删除（失效），8则表示彻底删除  多种情况可相加（8除外）',
  PRIMARY KEY (`orderhis_sysid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chargedb`.`producthis_sys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chargedb`.`producthis_sys` ;

CREATE TABLE IF NOT EXISTS `chargedb`.`producthis_sys` (
  `producthis_sysid` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NULL,
  `product_type` VARCHAR(25) NULL COMMENT '产品型号',
  `product_speci` VARCHAR(25) NULL COMMENT '规格',
  `product_unit` VARCHAR(25) NULL COMMENT '产品计量单位',
  `product_utprice` FLOAT NULL COMMENT '含税单价',
  `product_unprice` FLOAT NULL COMMENT '不含税单价',
  `product_remark` VARCHAR(55) NULL,
  `producthis_dealtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `product_id` VARCHAR(45) NULL,
  PRIMARY KEY (`producthis_sysid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chargedb`.`custid_sys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chargedb`.`custid_sys` ;

CREATE TABLE IF NOT EXISTS `chargedb`.`custid_sys` (
  `customer_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chargedb`.`prodid_sys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chargedb`.`prodid_sys` ;

CREATE TABLE IF NOT EXISTS `chargedb`.`prodid_sys` (
  `product_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
